<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_577117460fcd8',
	'title' => esc_html__( 'Front Page Banner Slider', 'terri' ),
	'fields' => array (
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'banner' => 'Banner',
				'slider' => 'Slider',
			),
			'default_value' => 'slider',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_57c690f4f898e',
			'label' => esc_html__( 'Banner or Slider', 'terri' ),
			'name' => 'front_page_banner_slider',
			'type' => 'radio',
			'instructions' => esc_html__( 'Choose between displaying a single banner or a slider on the front page.', 'terri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_57c6931f04c36',
			'label' => esc_html__( 'Banner Settings', 'terri' ),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57c690f4f898e',
						'operator' => '==',
						'value' => 'banner',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 0,
			'message' => '',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_57c6933104c37',
			'label' => esc_html__( 'Show Banner Overlay', 'terri' ),
			'name' => 'banner_overlay',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '#092d3b',
			'key' => 'field_57c6935804c38',
			'label' => esc_html__( 'Banner Overlay Colour', 'terri' ),
			'name' => 'banner_overlay_colour',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57c6933104c37',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'0.10' => '10%',
				'0.20' => '20%',
				'0.30' => '30%',
				'0.40' => '40%',
				'0.50' => '50%',
				'0.60' => '60%',
				'0.70' => '70%',
				'0.80' => '80%',
				'0.90' => '90%',
			),
			'default_value' => array (
				0 => '0.80',
			),
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_57c6938689e4f',
			'label' => esc_html__( 'Banner Overlay Opacity', 'terri' ),
			'name' => 'banner_overlay_opacity',
			'type' => 'select',
			'instructions' => esc_html__( 'Select the opacity of the slider overlay.', 'terri' ),
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57c6933104c37',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_57c693d5d5967',
			'label' => esc_html__( 'Banner', 'terri' ),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57c690f4f898e',
						'operator' => '==',
						'value' => 'banner',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'key' => 'field_57c694b406f1a',
			'label' => esc_html__( 'Banner Image', 'terri' ),
			'name' => 'banner_background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_57c694e506f1b',
			'label' => esc_html__( 'Banner Sub Title', 'terri' ),
			'name' => 'banner_sub_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_57c694fa06f1c',
			'label' => esc_html__( 'Banner Title', 'terri' ),
			'name' => 'banner_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'No Button' => 'No Button',
				'One Button' => 'One Button',
				'Two Buttons' => 'Two Buttons',
			),
			'default_value' => 'No Button',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_57c6950f06f1d',
			'label' => esc_html__( 'Banner Buttons', 'terri' ),
			'name' => 'banner_show_buttons',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'Internal Link' => 'Internal Link',
				'External Link' => 'External Link',
			),
			'default_value' => 'Internal Link',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_57c6955806f1e',
			'label' => esc_html__( 'Button One Link Type', 'terri' ),
			'name' => 'banner_link_one_link_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57c6950f06f1d',
						'operator' => '!=',
						'value' => 'No Button',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
			),
			'taxonomy' => array (
			),
			'allow_null' => 1,
			'multiple' => 0,
			'allow_archives' => 1,
			'key' => 'field_57c695a506f1f',
			'label' => esc_html__( 'Button One Link', 'terri' ),
			'name' => 'banner_link_one_internal_link',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57c6955806f1e',
						'operator' => '==',
						'value' => 'Internal Link',
					),
					array (
						'field' => 'field_57c6950f06f1d',
						'operator' => '!=',
						'value' => 'No Button',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'placeholder' => 'http://',
			'key' => 'field_57c6961a06f21',
			'label' => esc_html__( 'Button One Link', 'terri' ),
			'name' => 'banner_link_one_external_link',
			'type' => 'url',
			'instructions' => esc_html__( 'Use http://', 'terri' ),
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57c6955806f1e',
						'operator' => '==',
						'value' => 'External Link',
					),
					array (
						'field' => 'field_57c6950f06f1d',
						'operator' => '!=',
						'value' => 'No Button',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_57c6967b06f23',
			'label' => esc_html__( 'Button One Text', 'terri' ),
			'name' => 'banner_link_one_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57c6950f06f1d',
						'operator' => '!=',
						'value' => 'No Button',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'Colour' => 'Colour',
				'Border' => 'Border',
			),
			'default_value' => 'Colour',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_57c696b806f24',
			'label' => esc_html__( 'Button One Style', 'terri' ),
			'name' => 'banner_link_one_style',
			'type' => 'radio',
			'instructions' => esc_html__( 'Choose a between a button with a background colour or a border.', 'terri' ),
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57c6950f06f1d',
						'operator' => '!=',
						'value' => 'No Button',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'Internal Link' => 'Internal Link',
				'External Link' => 'External Link',
			),
			'default_value' => 'Internal Link',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_57c6970f06f25',
			'label' => esc_html__( 'Button Two Link Type', 'terri' ),
			'name' => 'banner_link_two_link_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57c6950f06f1d',
						'operator' => '==',
						'value' => 'Two Buttons',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
			),
			'taxonomy' => array (
			),
			'allow_null' => 1,
			'multiple' => 0,
			'allow_archives' => 1,
			'key' => 'field_57c6975406f26',
			'label' => esc_html__( 'Button Two Link', 'terri' ),
			'name' => 'banner_link_two_internal_link',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57c6970f06f25',
						'operator' => '==',
						'value' => 'Internal Link',
					),
					array (
						'field' => 'field_57c6950f06f1d',
						'operator' => '==',
						'value' => 'Two Buttons',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'placeholder' => 'http://',
			'key' => 'field_57c697a806f27',
			'label' => esc_html__( 'Button Two Link Type', 'terri' ),
			'name' => 'banner_link_two_external_link',
			'type' => 'url',
			'instructions' => esc_html__( 'Use http://', 'terri' ),
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57c6970f06f25',
						'operator' => '==',
						'value' => 'External Link',
					),
					array (
						'field' => 'field_57c6950f06f1d',
						'operator' => '==',
						'value' => 'Two Buttons',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_57c697e106f28',
			'label' => esc_html__( 'Button Two Text', 'terri' ),
			'name' => 'banner_link_two_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57c6950f06f1d',
						'operator' => '==',
						'value' => 'Two Buttons',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'Colour' => 'Colour',
				'Border' => 'Border',
			),
			'default_value' => 'Colour',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_57c6983606f29',
			'label' => esc_html__( 'Button Two Style', 'terri' ),
			'name' => 'banner_link_two_style',
			'type' => 'radio',
			'instructions' => esc_html__( 'Choose a between a button with a background colour or a border.', 'terri' ),
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57c6950f06f1d',
						'operator' => '==',
						'value' => 'Two Buttons',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 0,
			'message' => '',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_57c6a4c72c3eb',
			'label' => esc_html__( 'Show Request a Callback Form', 'terri' ),
			'name' => 'banner_show_form',
			'type' => 'true_false',
			'instructions' => esc_html__( 'Display a pre-defined request a callback form.', 'terri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'tabs' => 'text',
			'toolbar' => 'full',
			'media_upload' => 0,
			'default_value' => '',
			'delay' => 0,
			'key' => 'field_57c6a4fc2c3ec',
			'label' => esc_html__( 'Request a Callback Form', 'terri' ),
			'name' => 'banner_callback_form',
			'type' => 'wysiwyg',
			'instructions' => esc_html__( 'Paste shortcode for the chosen request a callback form here.', 'terri' ),
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57c6a4c72c3eb',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_577117aa627bc',
			'label' => esc_html__( 'Slider Settings', 'terri' ),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57c690f4f898e',
						'operator' => '==',
						'value' => 'slider',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 0,
			'message' => 'Check this to enable RTL for this slider.',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_577118a5fe91a',
			'label' => esc_html__( 'RTL Slider', 'terri' ),
			'name' => 'rtl_slider',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 0,
			'message' => '',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_57724c7d16952',
			'label' => esc_html__( 'Show Slider Overlay', 'terri' ),
			'name' => 'slider_overlay',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '#092d3b',
			'key' => 'field_57724c9816953',
			'label' => esc_html__( 'Slider Overlay Colour', 'terri' ),
			'name' => 'slider_overlay_colour',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57724c7d16952',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'0.10' => '10%',
				'0.20' => '20%',
				'0.30' => '30%',
				'0.40' => '40%',
				'0.50' => '50%',
				'0.60' => '60%',
				'0.70' => '70%',
				'0.80' => '80%',
				'0.90' => '90%',
			),
			'default_value' => array (
				0 => '0.80',
			),
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_57724cbc16954',
			'label' => esc_html__( 'Slider Overlay Opacity', 'terri' ),
			'name' => 'slider_overlay_opacity',
			'type' => 'select',
			'instructions' => esc_html__( 'Select the opacity of the slider overlay.', 'terri' ),
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57724c7d16952',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'slide' => 'Slide',
				'fade' => 'Fade',
			),
			'default_value' => array (
				0 => 'slide',
			),
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_587df5af998f7',
			'label' => esc_html__( 'Slider Animation Effect', 'terri' ),
			'name' => 'slider_effect',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 700,
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'ms',
			'key' => 'field_587df5fa998f8',
			'label' => esc_html__( 'Slider Speed', 'terri' ),
			'name' => 'slider_transition_speed',
			'type' => 'text',
			'instructions' => esc_html__( 'Set the slide transition speed in milliseconds. For example: 700 = 0.7 seconds.', 'terri' ),
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 1,
			'message' => '',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_587df641998f9',
			'label' => esc_html__( 'Auto Cycle Slides', 'terri' ),
			'name' => 'slider_auto_cycle',
			'type' => 'true_false',
			'instructions' => esc_html__( 'Automatically cycle slides.', 'terri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 3000,
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'ms',
			'key' => 'field_587df682998fa',
			'label' => esc_html__( 'Cycle Interval Time', 'terri' ),
			'name' => 'slider_cycle_interval',
			'type' => 'text',
			'instructions' => esc_html__( 'Time is set in milliseconds. For example: 3000 = 3 seconds.', 'terri' ),
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_587df641998f9',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_577117cf1725d',
			'label' => esc_html__( 'Slides', 'terri' ),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57c690f4f898e',
						'operator' => '==',
						'value' => 'slider',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'sub_fields' => array (
				array (
					'return_format' => 'url',
					'preview_size' => 'full',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'key' => 'field_577119a86a470',
					'label' => esc_html__( 'Image', 'terri' ),
					'name' => 'slider_background_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_57711b9bb0b5c',
					'label' => esc_html__( 'Sub Title', 'terri' ),
					'name' => 'slider_sub_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_57711b87b0b5b',
					'label' => esc_html__( 'Title', 'terri' ),
					'name' => 'slider_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'layout' => 'horizontal',
					'choices' => array (
						'No Button' => 'No Button',
						'One Button' => 'One Button',
						'Two Buttons' => 'Two Buttons',
					),
					'default_value' => 'No Button',
					'other_choice' => 0,
					'save_other_choice' => 0,
					'allow_null' => 0,
					'return_format' => 'value',
					'key' => 'field_577120fde1124',
					'label' => esc_html__( 'Slider Buttons', 'terri' ),
					'name' => 'slider_show_buttons',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'layout' => 'horizontal',
					'choices' => array (
						'Internal Link' => 'Internal Link',
						'External Link' => 'External Link',
					),
					'default_value' => 'Internal Link',
					'other_choice' => 0,
					'save_other_choice' => 0,
					'allow_null' => 1,
					'return_format' => 'value',
					'key' => 'field_57711bacb0b5d',
					'label' => esc_html__( 'Button One Link Type', 'terri' ),
					'name' => 'slider_link_one_link_type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_577120fde1124',
								'operator' => '!=',
								'value' => 'No Button',
							),
						),
					),
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
				),
				array (
					'post_type' => array (
					),
					'taxonomy' => array (
					),
					'allow_null' => 1,
					'multiple' => 0,
					'allow_archives' => 1,
					'key' => 'field_57711cd9b0b5e',
					'label' => esc_html__( 'Button One Link', 'terri' ),
					'name' => 'slider_link_one_internal_link',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57711bacb0b5d',
								'operator' => '==',
								'value' => 'Internal Link',
							),
							array (
								'field' => 'field_577120fde1124',
								'operator' => '!=',
								'value' => 'No Button',
							),
						),
					),
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'placeholder' => 'http://',
					'key' => 'field_57711d1bb0b5f',
					'label' => esc_html__( 'Button One Link', 'terri' ),
					'name' => 'slider_link_one_external_link',
					'type' => 'url',
					'instructions' => esc_html__( 'Use http://', 'terri' ),
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57711bacb0b5d',
								'operator' => '==',
								'value' => 'External Link',
							),
							array (
								'field' => 'field_577120fde1124',
								'operator' => '!=',
								'value' => 'No Button',
							),
						),
					),
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_57711d70b0b60',
					'label' => esc_html__( 'Button One Text', 'terri' ),
					'name' => 'slider_link_one_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_577120fde1124',
								'operator' => '!=',
								'value' => 'No Button',
							),
						),
					),
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'layout' => 'horizontal',
					'choices' => array (
						'Colour' => 'Colour',
						'Border' => 'Border',
					),
					'default_value' => 'Colour',
					'other_choice' => 0,
					'save_other_choice' => 0,
					'allow_null' => 0,
					'return_format' => 'value',
					'key' => 'field_57711d8cb0b61',
					'label' => esc_html__( 'Button One Style', 'terri' ),
					'name' => 'slider_link_one_style',
					'type' => 'radio',
					'instructions' => esc_html__( 'Choose a between a button with a background colour or a border.', 'terri' ),
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_577120fde1124',
								'operator' => '!=',
								'value' => 'No Button',
							),
						),
					),
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
				),
				array (
					'layout' => 'horizontal',
					'choices' => array (
						'Internal Link' => 'Internal Link',
						'External Link' => 'External Link',
					),
					'default_value' => 'Internal Link',
					'other_choice' => 0,
					'save_other_choice' => 0,
					'allow_null' => 1,
					'return_format' => 'value',
					'key' => 'field_57711db7b0b62',
					'label' => esc_html__( 'Button Two Link Type', 'terri' ),
					'name' => 'slider_link_two_link_type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_577120fde1124',
								'operator' => '==',
								'value' => 'Two Buttons',
							),
						),
					),
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
				),
				array (
					'post_type' => array (
					),
					'taxonomy' => array (
					),
					'allow_null' => 1,
					'multiple' => 0,
					'allow_archives' => 1,
					'key' => 'field_57711ddfb0b63',
					'label' => esc_html__( 'Button Two Link', 'terri' ),
					'name' => 'slider_link_two_internal_link',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57711db7b0b62',
								'operator' => '==',
								'value' => 'Internal Link',
							),
							array (
								'field' => 'field_577120fde1124',
								'operator' => '==',
								'value' => 'Two Buttons',
							),
						),
					),
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'placeholder' => 'http://',
					'key' => 'field_57711df3b0b64',
					'label' => esc_html__( 'Button Two Link', 'terri' ),
					'name' => 'slider_link_two_external_link',
					'type' => 'url',
					'instructions' => esc_html__( 'Use http://', 'terri' ),
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57711db7b0b62',
								'operator' => '==',
								'value' => 'External Link',
							),
							array (
								'field' => 'field_577120fde1124',
								'operator' => '==',
								'value' => 'Two Buttons',
							),
						),
					),
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_57711e07b0b65',
					'label' => esc_html__( 'Button Two Text', 'terri' ),
					'name' => 'slider_link_two_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_577120fde1124',
								'operator' => '==',
								'value' => 'Two Buttons',
							),
						),
					),
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'layout' => 'horizontal',
					'choices' => array (
						'Colour' => 'Colour',
						'Border' => 'Border',
					),
					'default_value' => 'Colour',
					'other_choice' => 0,
					'save_other_choice' => 0,
					'allow_null' => 0,
					'return_format' => 'value',
					'key' => 'field_57711e18b0b66',
					'label' => esc_html__( 'Button Two Style', 'terri' ),
					'name' => 'slider_link_two_style',
					'type' => 'radio',
					'instructions' => esc_html__( 'Choose a between a button with a background colour or a border.', 'terri' ),
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_577120fde1124',
								'operator' => '==',
								'value' => 'Two Buttons',
							),
						),
					),
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => 0,
					'message' => '',
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'key' => 'field_57c283b50c166',
					'label' => esc_html__( 'Show Request a Callback Form', 'terri' ),
					'name' => 'slider_show_form',
					'type' => 'true_false',
					'instructions' => esc_html__( 'Display a pre-defined request a callback form.', 'terri' ),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'tabs' => 'text',
					'toolbar' => 'full',
					'media_upload' => 0,
					'default_value' => '',
					'delay' => 0,
					'key' => 'field_57c283f70c167',
					'label' => esc_html__( 'Request a Callback Form', 'terri' ),
					'name' => 'slider_callback_form',
					'type' => 'wysiwyg',
					'instructions' => esc_html__( 'Paste shortcode for the chosen request a callback form here.', 'terri' ),
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57c283b50c166',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
				),
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Slide',
			'collapsed' => '',
			'key' => 'field_577119426a46f',
			'label' => esc_html__( 'Slide', 'terri' ),
			'name' => 'slider_slide',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
			array (
				'param' => 'page_type',
				'operator' => '!=',
				'value' => 'posts_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_57dfe68930184',
	'title' => esc_html__( 'Project Gallery', 'terri' ),
	'fields' => array (
		array (
			'layout' => 'horizontal',
			'choices' => array (
				1 => '1',
				2 => '2',
				3 => '3',
				4 => '4',
			),
			'default_value' => 3,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_57dfffb98e3e3',
			'label' => esc_html__( 'Gallery Columns', 'terri' ),
			'name' => 'project_gallery_columns',
			'type' => 'radio',
			'instructions' => esc_html__( 'Select the number of images in each row', 'terri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'library' => 'all',
			'min' => '',
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'insert' => 'append',
			'key' => 'field_57dfe69bd731b',
			'label' => esc_html__( 'Gallery Images', 'terri' ),
			'name' => 'project_gallery_images',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 0,
			'message' => '',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_57e25179b3033',
			'label' => esc_html__( 'Show Gallery Content', 'terri' ),
			'name' => 'show_project_gallery_content',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'default_value' => '',
			'delay' => 0,
			'key' => 'field_57e25137b3032',
			'label' => esc_html__( 'Gallery Content', 'terri' ),
			'name' => 'project_gallery_content',
			'type' => 'wysiwyg',
			'instructions' => esc_html__( 'Add extra content to be shown below the gallery images.', 'terri' ),
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57e25179b3033',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'project',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_579f001f17c51',
	'title' => esc_html__( 'Page Title', 'terri' ),
	'fields' => array (
		array (
			'placement' => 'left',
			'endpoint' => 0,
			'key' => 'field_579f0235d5714',
			'label' => esc_html__( 'Titles', 'terri' ),
			'name' => 'titles',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_579f00bcc816a',
			'label' => esc_html__( 'Subtitle', 'terri' ),
			'name' => 'page_subtitle',
			'type' => 'text',
			'instructions' => esc_html__( 'Set a custom sub title for a page, post, project, service or team member.', 'terri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_579f009ec8169',
			'label' => esc_html__( 'Title', 'terri' ),
			'name' => 'page_title',
			'type' => 'text',
			'instructions' => esc_html__( 'Set a custom title for a page, post, project, service or team member. This overwrites the standard title.', 'terri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'placement' => 'left',
			'endpoint' => 0,
			'key' => 'field_579f029de4e1b',
			'label' => esc_html__( 'Settings', 'terri' ),
			'name' => '_copy',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '#FAB709',
			'key' => 'field_579f017d71295',
			'label' => esc_html__( 'Subtitle Colour', 'terri' ),
			'name' => 'page_subtitle_colour',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '#092d3b',
			'key' => 'field_579f016471294',
			'label' => esc_html__( 'Title Colour', 'terri' ),
			'name' => 'page_title_colour',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'Left' => 'Left',
				'Centre' => 'Centre',
				'Right' => 'Right',
			),
			'default_value' => 'Left',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_579f102b22f42',
			'label' => esc_html__( 'Title Text Align', 'terri' ),
			'name' => 'page_title_text_align',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'small' => 'Small',
				'large' => 'Large',
			),
			'default_value' => 'small',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_57ab27a9159b2',
			'label' => esc_html__( 'Page Title Size', 'terri' ),
			'name' => 'page_title_size',
			'type' => 'radio',
			'instructions' => esc_html__( 'Choose between small and large height for the page title.', 'terri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'Background Image' => 'Background Image',
				'Background Colour' => 'Background Colour',
			),
			'default_value' => 'Background Colour',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_579f119c7b3d5',
			'label' => esc_html__( 'Page Title Background Settings', 'terri' ),
			'name' => 'page_title_background_settings',
			'type' => 'radio',
			'instructions' => esc_html__( 'Choose whether the page title background will display an image or a background colour.', 'terri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'left',
			'endpoint' => 0,
			'key' => 'field_579f03e6d09d9',
			'label' => esc_html__( 'Background Image', 'terri' ),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_579f119c7b3d5',
						'operator' => '==',
						'value' => 'Background Image',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'key' => 'field_579f04295e6fe',
			'label' => esc_html__( 'Background Image', 'terri' ),
			'name' => 'page_title_background_image',
			'type' => 'image',
			'instructions' => esc_html__( 'Choose a background image to be used in the background of the page title area.', 'terri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'pattern' => 'Repeating Pattern',
				'large_image' => 'Large Image',
			),
			'default_value' => 'large_image',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_579f05621e958',
			'label' => esc_html__( 'Background Image Type', 'terri' ),
			'name' => 'page_title_background_image_type',
			'type' => 'radio',
			'instructions' => esc_html__( 'Choose whether the page title background image will be a repeating pattern or a large image that covers the area.', 'terri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 0,
			'message' => '',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_579f13618bfb7',
			'label' => esc_html__( 'Background Image Overlay', 'terri' ),
			'name' => 'page_title_background_image_overlay',
			'type' => 'true_false',
			'instructions' => esc_html__( 'Select yes if you choose to display the theme defined overlay colour over the page title background image.', 'terri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'left',
			'endpoint' => 0,
			'key' => 'field_579f11f97b3d6',
			'label' => esc_html__( 'Background Colour', 'terri' ),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_579f119c7b3d5',
						'operator' => '==',
						'value' => 'Background Colour',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_579f012d71293',
			'label' => esc_html__( 'Background Colour', 'terri' ),
			'name' => 'page_title_background_colour',
			'type' => 'color_picker',
			'instructions' => esc_html__( 'Select a background colour for the page title area.', 'terri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
			array (
				'param' => 'page_type',
				'operator' => '!=',
				'value' => 'posts_page',
			),
			array (
				'param' => 'page_type',
				'operator' => '!=',
				'value' => 'front_page',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array (
				'param' => 'page_type',
				'operator' => '!=',
				'value' => 'posts_page',
			),
			array (
				'param' => 'page_type',
				'operator' => '!=',
				'value' => 'front_page',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'project',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'team',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_57bde2d1c50cb',
	'title' => esc_html__( 'Sidebar Settings', 'terri' ),
	'fields' => array (
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'hide' => 'Hide',
				'left' => 'Left',
				'right' => 'Right',
			),
			'default_value' => 'right',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_57bde2e31054c',
			'label' => esc_html__( 'Show or Hide Sidebar', 'terri' ),
			'name' => 'show_hide_sidebar',
			'type' => 'radio',
			'instructions' => esc_html__( 'Choose to hide sidebar or display left or right sidebar for this page', 'terri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_type',
				'operator' => '!=',
				'value' => 'front_page',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'template-full-width.php',
			),
			array (
				'param' => 'post_type',
				'operator' => '!=',
				'value' => 'project',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;